### ISSUE TITLE
Android modal loads redirectURI into modal

### ISSUE THREAD

**Issue by cidevant** [xcarpentier/react-native-linkedin#111] opened 2018-12-19 09:37 UTC
#### Issue Description

IOS works as it should. But on android, I have **installed LinkedIn** app and when I login in modal window, it don't closes. But it loads "redirectURI" into modal. 

#### Steps to Reproduce / Code Snippets

Just try to login

#### Expected Results

Modal should be closed, and "onSuccess" must be triggered.

#### Additional Information

* Nodejs version: v10.13.0
* React version: 16.6.0-alpha.8af6728
* React Native version: 0.57.3
* react-native-linkedin version: ^1.3.1
* Platform(s) (iOS, Android, or both?): android

**Comment by tranhiepqna** [comment] 2018-12-25 04:35
Do you have any solution for this issue?

**Comment by Saumyadip-Pramanik** [comment] 2019-01-04 07:45
Need a solution...

**Comment by xcarpentier** [comment] 2019-01-09 13:55
Sorry about that...
PR are welcome !

**Comment by honzadvorak** [comment] 2019-01-16 14:23
yes, facing exactly the same problem :-(

**Comment by cidevant** [comment] 2019-01-18 13:33
I found the problem, but dont know how to solve it. On Android, there is a problem with "this.onLoadStart" and Linkedin's submit button. 

As you can see on IOS screenshot: `this.onLoadStart` is triggered  3 times after user clicks on linkedin's button "SIGN IN". In IOS **every** server redirect is catched by `this.onLoadStart`.

IOS SCREENSHOT
![capture](https://i.imgur.com/RSC5zqC.png)

On Android `this.onLoadStart` **donsn't catch** server redirects and ONLY triggers `this.onLoadStart` with final redirected URL. In my case `bassoe.no/linkedin-auth/?xxx` redirects to `bassoe.no/analytics`.

ANDROID SCREENSHOT
![capture](https://i.imgur.com/ARQyA7v.png)

In my screenshots, for better understanding and debugging I renamed/moved those functions:
1) [onLoadStart](https://github.com/xcarpentier/react-native-linkedin/blob/master/index.js#L136) to **[this.processUrl]**
2) **[this.onLoadStart]** is refering to this function [this.onLoadStart](https://github.com/xcarpentier/react-native-linkedin/blob/master/index.js#L237)

**Comment by cidevant** [comment] 2019-01-18 13:40
@xcarpentier Do you have any ideas how to solve this?

**Comment by cidevant** [comment] 2019-01-18 14:55
Solved! Use "react-native-webview" instead!

**Comment by paour** [comment] 2019-01-18 15:10
Closing the issue doesn't seem very constructive. It's your right as OP, but several other people would like to still use this library, once it's fixed.

**Comment by cidevant** [comment] 2019-01-18 15:19
@paour As you wish
@xcarpentier Waiting for fix. I would submit pull-request, but have no idea how to link `react-native-webview` to this package, which has no `android` and `ios` folders.

**Comment by paour** [comment] 2019-01-18 15:23
@cidevant have you been able to reliably reproduce this issue? In my case, it seems to be the result of a race condition: I have very seldom reproduced it on my dev setup, but it happens quite frequently on user devices in release builds, where it's too late to effectively debug it.

**Comment by cristin** [comment] 2019-01-29 16:18
Hi all!

Are there any updates on this issue or an estimate by when it could be fixed?

Thanks!

**Comment by cidevant** [comment] 2019-02-04 16:11
@cristin There are not details. Native "WebView" on Android (from react-native), doesn't catch redirections (HTTP 30x) at all (while react-native-webview catches them all). The whole point of this package is **WATCHING REDIRECTS**, and if it matched "redirectURI" you specifed - it triggers successful callback.

**Comment by cidevant** [comment] 2019-02-04 16:14
Catch redirection - I mean triggering "this.onLoadStart" callback when url of webview is changed.

**Comment by xcarpentier** [comment] 2019-02-07 15:57
It's weird that android don't follow redirect... maybe we have to change the `onLoadStart` by another listening event like `onNavigationStateChange `

**Comment by cidevant** [comment] 2019-02-12 14:55
@xcarpentier I tried it! Only WebView from "react-native-webview" works. As you can see on official react-native site, they are deprecating WebView from "react-native": https://facebook.github.io/react-native/docs/webview

**Comment by xcarpentier** [comment] 2019-02-12 15:07
This deprecation does not mean under featured webview, that just mean react-native team delegate the work to the community but webview still here.

I'm using this `onNavigationStateChange` for other customer project and I deal with the redirect from android, Please recheck :)

**Comment by cidevant** [comment] 2019-02-12 15:13
@xcarpentier I am not the only one, who is facing this problem. If you don't want to fix it, just close the ticket.

**Comment by xcarpentier** [comment] 2019-02-12 15:22
Pardon if I'm disturbed you. I'm not like that and don't want to be.

I want to fix it, but change the behavior of the lib is not really funny for me. I want to keep it as simple as it is now.
And I'm not really sure that you are right because as I said I'm using webview in almost the same context with a pretty earlier version of react-native and I didn't notice any modification **if** I use `onNavigationStateChange`

Please reference where I can find other issues concerning **redirection**.
Thank you :)

**Comment by cidevant** [comment] 2019-02-12 15:51
@xcarpentier 

> Please reference where I can find other issues concerning **redirection**.

Comments of other people in this issue is not enough?
https://github.com/xcarpentier/react-native-linkedin/issues/111#issuecomment-451372290
https://github.com/xcarpentier/react-native-linkedin/issues/111#issuecomment-449799919
https://github.com/xcarpentier/react-native-linkedin/issues/111#issuecomment-452402063
https://github.com/xcarpentier/react-native-linkedin/issues/111#issuecomment-454796967
https://github.com/xcarpentier/react-native-linkedin/issues/111#issuecomment-455582890

> And I'm not really sure that you are right...

If screenshots I provided are not enough, here you have video. If it works for you, it doesn't mean that it works for everyone.

[Video link](https://drive.google.com/file/d/1dLdUtzpKkAZTcLs2Kz3BkFwdVIOiADlR)

**Comment by xcarpentier** [comment] 2019-02-12 16:15
Thank you, will figure out.

**Comment by xcarpentier** [comment] 2019-02-12 16:16
BTW I change master with `onNavigationStateChange` and if someone has the chance to test it, please let us know.

**Comment by cidevant** [comment] 2019-02-12 16:22
@xcarpentier As I said before, I already tried to use `onNavigationStateChange` instead of `onLoadStart`. You don't listen to me. The only way is to import WebView from `react-native-webview`.

**Comment by xcarpentier** [comment] 2019-02-12 16:31
So I'm sad about this solution... this why I try another

**Comment by xcarpentier** [comment] 2019-02-12 16:57
https://stackoverflow.com/questions/50126168/webview-onnavigationstatechange-returns-url-of-previous-page

**Comment by cidevant** [comment] 2019-02-12 17:18
Yes, I know it... I tried and result is the  same: android dont catch redirects((( I spent more than 10 hours of debugging and trying to make this package pure js, but I failed(((

**Comment by phbn** [comment] 2019-03-11 13:16
Hi, is any help needed to author, issue and push a fix?

**Comment by tannera** [comment] 2019-03-19 14:49
Any temporary workarounds?

**Comment by xcarpentier** [comment] 2019-04-12 09:38
The issue for me is to abandon simple expo support with a usage of react-native-webview...

**Comment by maulikdhameliya** [comment] 2019-04-16 13:28
Hello @xcarpentier , I think many people started to face this issue including `me`.  

I started to integrate 'react-native-webview' as many people here suggested but got build errors.
https://github.com/react-native-community/react-native-webview/issues/55
Since my app is in production and not using latest React version and using very old React version

I am not sure how to come out of this deadlock situation.

**Comment by maulikdhameliya** [comment] 2019-04-18 08:12
@cidevant @xcarpentier I have fixed my problem.
I was getting events in `onNavigationStateChange` but below condition was not getting executed properly and hence not able to close the modal.
https://github.com/xcarpentier/react-native-linkedin/blob/d18157e2b25cbea87c46537bd3b3ea9fb3a7a97b/index.js#L241


for me the problem was with https and http and since I have put many redirection link in linkedin developer console.
check if redirectionUrl is correct and matching with what you have put in code. 
silly issue isn't it (atleast for me)

I hope this helps someone.

**Comment by xcarpentier** [comment] 2019-04-18 10:47
Thanks 🎉
Is it possible for you to create PR?

**Comment by maulikdhameliya** [comment] 2019-04-19 04:24
@xcarpentier  no need to change in library

**Comment by phbn** [comment] 2019-06-20 11:21
Still struggling with this issue.

> The issue for me is to abandon simple expo support with a usage of react-native-webview...

As I can tell they have added react-native-webview support in the newest Expo SDK (v33). (https://expo.canny.io/feature-requests/p/react-native-webview-support)
Does this solve your issue of dropping simple expo support by switching to react native webview for solution?

**Closed** 2019-08-26 11:34 UTC
Labels: wontfix
